### PR TITLE
terraform for OCI

### PR DESCRIPTION
**Pull request by mikarinneoracle**
Hi, extended this extension to work with Oracle Cloud Infrastructure (OCI).
Please review and test. I've tested this using Azure runner/agent on OCI Oracle Linux and Windows VMs.

For the OCI config please create a local oci cli config first and then upload the public generated auth token to the user profile in OCI and then copy the values to the Azure Devops OCI service connection (i.e. backend connection) config including the generated private auth token.

Optional:
To use a remote Terraform statefile in OCI object storage create an object storage buckect for the OCI user to store the state file and then create a PAR for it (preauthenticated request) and configure the PAR to the extension and then select 'yes' to generate the Terraform remote state file config. Otherwise choose 'no'.

Example PAR:
https://objectstorage.eu-amsterdam-1.oraclecloud.com/p/MqM0Iu1E6DXSYVjS...epuSMWY8o/n/tenancy_namespace/b/tf-state/o/terraform.tfstate

### CODE REVIEW

**Comment by mikarinneoracle** [comment]
How do I agree to the policy @microsoft-github-policy-service agree ?

**Comment by mikarinneoracle** [comment]
@mericstam Can you please help/have a look ? :)

**Comment by mikarinneoracle** [comment]
@https://github.com/microsoftopensource Can you please help/have a look ? :)

**Review by mericstam — APPROVED** [review]
LGTM

**Pull request merged**
