### PR TITLE
Users/mericstam/add v3 terraform task

### PR DESCRIPTION
**Pull request by mericstam**
Prepare for V3

### CODE REVIEW

**Comment by joskuijpers-imec** [comment]
Hi, what is the state of this PR? I'd like to use the 'custom' command for running 'fmt --check'.

**Comment by mericstam** [comment]
Now that all security and other important update are done and released, this finalizing this PR is next on my agenda. I need to retrofit some of the recent updates from V2.  But aiming for next week.

**Comment by joskuijpers-imec** [comment]
Sounds great, thank you. For now I have used the Terraform Installer and then a script task.

**Review by madkoo — APPROVED** [review]
LGTM

**Comment by UP932296** [comment]
When is this due to be merged? Keen to use this ASAP

**Pull request merged**
